### ISSUE TITLE
FNX-4441 ⁃ [Bug] I can't click on items at the bottom of the page

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla-mobile/fenix#10636]
## Steps to reproduce
set url bar to bottom.
visit reddit, log in
go to https://www.reddit.com/r/firefox/new/
scroll down
click next on the bottom right corner
![Screenshot](https://user-images.githubusercontent.com/922368/81867437-5d78ca00-9579-11ea-8db3-4fb035bcdaea.png)UNITO-UNDERSCORE!20200514-002055!UNITO-UNDERSCORE!Firefox!UNITO-UNDERSCORE!Nightly!

browser.urlbar.richSuggestions.tail", false);

### Expected behavior
I see the next reddit page

### Actual behavior
I'm on the same page

### Device information
* Android device: one plus 5t
* Fenix version: nightly

**Comment by andreicristianpetcu** [comment]
I can't post a comment on reddit due to this. I can't close the comment box once I open it. Reddit puts a lot of buttons at the bottom :(

**Comment by Rodze** [comment]
The bug also happens to me to buttons eventually placed at the end of the simple version of Reddit pages, accessible by appending ". compact" at the end of any URL.

**Comment by andreicristianpetcu** [comment]
I want Fenix to works well with the standard version of Reddit.

**Comment by andreicristianpetcu** [comment]
would running mozregression on this help?

**Comment by emilio** [comment]
Yes, running mozregression on this would definitely be helpful, I suspect.

**Comment by pro-wh** [comment]
Is it coincidental that the unhittable area is about as high as the hidden URL bar?

**Comment by karlcow** [comment]
Another issue which looks very similar https://github.com/webcompat/web-bugs/issues/52871

**Comment by karlcow** [comment]
Yes the position of the item near the bottom has influence 

1. Go to http://prelive-car.touch-ins.co.il/
2. Use Test, Test, example@gmail.com, 0581234567
3. Select the checkbox 
4. Tap on the submit button 

The console on tap.

```
touchstart { target: html
, isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, metaKey: false, ctrlKey: false, shiftKey: false, view: Window, … }
polyfills-es2015.073f70090846b1e1e40d.js:42:981

Empty string passed to getElementById(). 3 prelive-car.touch-ins.co.il

mousedown { target: label
, buttons: 0, clientX: 95, clientY: 491, layerX: 54, layerY: 33 }
polyfills-es2015.073f70090846b1e1e40d.js:42:981

​```

so if it's just a question of being at the bottom of the screen let's increase the space at the bottom for testing.

```css

/* Inline #4 | http://prelive-car.touch-ins.co.il/ */

body {
		margin-bottom: 200px;
}
```

Let's try to tap again. and this time we get 

```css
touchstart { target: span
, isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, metaKey: false, ctrlKey: false, shiftKey: false, view: Window, … }
polyfills-es2015.073f70090846b1e1e40d.js:42:981

touchstart { target: span
, isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, metaKey: false, ctrlKey: false, shiftKey: false, view: Window, … }
polyfills-es2015.073f70090846b1e1e40d.js:42:780

touchend { target: span
, isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false, metaKey: false, ctrlKey: false, shiftKey: false, view: Window, … }
polyfills-es2015.073f70090846b1e1e40d.js:42:780

mousedown { target: span
, buttons: 0, clientX: 102, clientY: 489, layerX: 61, layerY: 19 }
polyfills-es2015.073f70090846b1e1e40d.js:42:981

mousedown { target: span
, buttons: 0, clientX: 102, clientY: 489, layerX: 61, layerY: 19 }
polyfills-es2015.073f70090846b1e1e40d.js:42:780

mouseup { target: span
, buttons: 0, clientX: 102, clientY: 489, layerX: 61, layerY: 19 }
polyfills-es2015.073f70090846b1e1e40d.js:42:780

click { target: span
, buttons: 0, clientX: 102, clientY: 489, layerX: 61, layerY: 19 }
polyfills-es2015.073f70090846b1e1e40d.js:42:780

click { target: span, buttons: 0, clientX: 102, clientY: 488, layerX: 0, layerY: 0 }
polyfills-es2015.073f70090846b1e1e40d.js:42:780
```
