### ISSUE TITLE
[Bug] `-webkit-fill-available` doesn't work on the `html` element

### ISSUE THREAD

**Issue by kripod** [mozilla-mobile/fenix#13870]
## Steps to reproduce

Use the code below as suggested [on CSS Tricks](https://css-tricks.com/css-fix-for-100vh-in-mobile-webkit/):

```css
body {
  min-height: 100vh;
  min-height: -webkit-fill-available;
}
html {
  height: -webkit-fill-available;
}
```

Please try out the [demo page](https://output.jsbin.com/noqasek/quiet) provided by @simevidas.

### Expected behavior

The content should fill the viewport vertically, without the URL bar hiding the footer.

### Actual behavior

As described in https://github.com/postcss/postcss-100vh-fix/issues/1#issuecomment-674562209, the URL bar overlaps the footer.

### Device information

* Android device: Android 7.0 (on Moto G4)
* Fenix version: Firefox Nightly, build #2015758065
