### ISSUE TITLE
[Bug] [Pull to refresh] m.twitter.com can't seem to override pull-to-refresh behavior.

### ISSUE THREAD

**Issue by emilio** [mozilla-mobile/fenix#16599]
## Steps to reproduce

 * Open mobile.twitter.com
 * Pull to refresh

### Expected behavior

 * Twitter has a custom pull to refresh behavior which works in Chrome.

### Actual behavior

 * Pull to refresh doesn't work.

### Device information

* Android device: N/A (repros on emulator)
* Fenix version: Latest nightly.

**Comment by emilio** [comment]
I think this might be a Twitter bug.

They have:

```css
body {
    -ms-overflow-style: scrollbar;
    overflow-y: scroll;
    overscroll-behavior-y: none;
}
```

But `overscroll-behavior-y` on `body` is supposed to do nothing per spec.

It [does](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/dom/document.cc;l=2261-2267;drc=d0e87c5b5ac8f1d884f5899f4b63967fea784d07) on Chromium though. It's a known Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=954423
