### ISSUE TITLE
Migrating to newer Glean Events API (introduced with Glean v39)

### ISSUE THREAD

**Issue by badboy** [mozilla-mobile/fenix#19967]
[API Reference for Events](https://mozilla.github.io/glean/book/reference/metrics/event.html)

Glean gained type annotations for extra keys, allowing for `string`, `boolean` and `quantity` (a numeric value).
This changes the calling API if specified.
**Note**: Data is still sent stringified.

Old metrics definition:

```yaml
views:
  login_opened:
    type: event
    description: |
      Recorded when the login view is opened.
    extra_keys:
      source_of_login:
        description: The source
    ...
```

New metrics definition:

```yaml
views:
  login_opened:
    type: event
    description: |
      Recorded when the login view is opened.
    extra_keys:
      source_of_login:
        type: string
        description: The source
    ...
```

Old calling API:

```kotlin
import org.mozilla.yourApplication.GleanMetrics.Views

Views.loginOpened.record(mapOf(Views.loginOpenedKeys.sourceOfLogin to "toolbar"))
```

New calling API:

```kotlin
import org.mozilla.yourApplication.GleanMetrics.Views

Views.loginOpened.record(Views.loginOpenedExtra(sourceOfLogin = "toolbar"))
```

The old calling API is deprecated as of Glean v39 (June 2021).
There are currently no plans for full removal of the deprecated API.
Any removal will only happen in another major version release and communicated accordingly.
