### ISSUE TITLE
[Bug]: @media(hover: hover) is true but should be false

### ISSUE THREAD

**Issue by hirasso** [mozilla-mobile/fenix#21255]
### Steps to reproduce

1. write some css like the following in a HTML page with no other styles:
```css
body {
    background: green;
}
@media (hover: hover) {
    body {
        background: yellow;
    }
}
```
2. open the page in firefox on your touch-only android device

### Expected behaviour

The page should be green, since I am visiting it from the firefox browser on my android device

### Actual behaviour

The page is yellow, somehow the `@media(hover: hover)` seems to fire

### Device name

Google Pixel 5

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

92.1. I 1
