### ISSUE TITLE
[Bug]: Text is rendered incorrectly

### ISSUE THREAD

**Issue by ghollf** [mozilla-mobile/fenix#25555]
### Steps to reproduce

https://m.bild.de/

### Expected behaviour

Text is rendered as it is with different web engines

### Actual behaviour

Text on images is hardly readable because color is rendered incorrectly

### Android version

Android 10

### Firefox release type

Firefox

### Firefox version

101.1.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20667)

**Comment by Mugurell** [comment]
@ghollf Can you please post a screenshot showcasing the issue?
I tried it now and the images and text seem to be rendered as expected.

https://user-images.githubusercontent.com/11428869/172635779-81e18f1d-2153-4554-87a3-5f2e8c0d2d3f.mp4

&nbsp;

I see there many versions of this website are archived already - https://web.archive.org/web/*/https://m.bild.de/
Reproducing the issue on a particular snapshot would greatly help in identifying the issue.

**Comment by ghollf** [comment]
> @ghollf Can you please post a screenshot showcasing the issue? Also interested in the settings for "Enhanced Tracking Protection" you're using. I tried it now and the images and text seem to be rendered as expected.
> bildde.mp4
> 
>  
> 
> I see there many versions of this

**Comment by ghollf** [comment]
![Screenshot_20220608-222849](https://user-images.githubusercontent.com/38644565/172719304-22c88d30-a3ba-4244-b0d9-b2b36bb38bbf.png)
![Screenshot_20220608-225447](https://user-images.githubusercontent.com/38644565/172719278-e1b4cbea-b133-4f53-b233-e6de47989534.png)

**Comment by Mugurell** [comment]
Tried to reproduce this but I couldn't. Trying to find the same page structure with the help of https://web.archive.org/web/*/https://m.bild.de/ shows not images being loaded.
Seeing in your screenshots the private mode being used I'm curious if this is needed to reproduce the issue? And generally any other correlations that could get the same part of the page being rendered differently. 
Moving to Bugzilla for more investigations by the layout team. Please followup there for progress.

**Comment by Mugurell** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1773441

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by emilio** [comment]
I can't repro this either. Do you have any extension active that could cause this? (Dark Reader perhaps?)

**Comment by dholbert** [comment]
I can reproduce this in Chrome (on Desktop) with Responsive Design Mode, too:
![image](https://user-images.githubusercontent.com/426803/172928422-fa0bbd46-a19e-47ec-a62b-08cebfe19bbe.png)

In both Chrome and Firefox, the issue seems to happen with a viewport width of precisely 600px (for me at least), at which point this CSS rule matches and gives a dark-gray color to the text:
```css
@media (min-width: 0) and (max-width: 37.5em)
.stage-teaser.bottom-to-overlay .red-teaser-title__headline {
    color: #212529;
    margin-top: 0;
```
...and this CSS rule also matches which is what overlays the headline on top of the image:
```css:
@media (min-width: 37.5em)
.stage-teaser.bottom-to-overlay .red-teaser-title {
    position: absolute;
    bottom: 0;
    width: 100%;
    margin: 0;
    text-align: center;
[...]
}


So this is just a bug in the website's CSS, where `37.5em` is a magic tipping-point where CSS rules from two different designs end up applying.  And it's not a Firefox-specific issue.

The reporter just happens to be unlucky enough that 37.5em happens to precisely match their viewport width in Firefox, whereas in Chrome, 37.5em must be barely-smaller-than their viewport width.  (Not too surprising and not-a-bug for there to be a subtle disagreement on resolving that value, since `em` lengths are font-metrics-dependent.)

**Comment by dholbert** [comment]
It looks like Bild could fix this by simply swapping the order of these two CSS rules and adding a media query:
```css
.stage-teaser.bottom-to-overlay .red-teaser-title__headline {
 text-shadow:1px 2px 8px rgba(0,0,0,.6);
 color:#fff;
 margin-top:4px
}
@media(min-width:0)and (max-width:37.5em) {
 .stage-teaser.bottom-to-overlay .red-teaser-title__headline {
  display:-webkit-box;
  -webkit-line-clamp:3;
  -webkit-box-orient:vertical;
  overflow:hidden;
  text-shadow:none;
  color:#212529;
  margin-top:0
 }
}
```

i.e. replacing this^ CSS with the folllowing:
```css
@media(min-width:0)and (max-width:37.5em) {
 .stage-teaser.bottom-to-overlay .red-teaser-title__headline {
  display:-webkit-box;
  -webkit-line-clamp:3;
  -webkit-box-orient:vertical;
  overflow:hidden;
  text-shadow:none;
  color:#212529;
  margin-top:0
 }
}
@media(min-width:37.5em) {
 .stage-teaser.bottom-to-overlay .red-teaser-title__headline {
  text-shadow:1px 2px 8px rgba(0,0,0,.6);
  color:#fff;
  margin-top:4px
 }
}
```

With the order swapped (as in my second snippet here), the `#fff` coloring will "win" in the cascade when we're at the magic viewport-width of 37.5em (at which point their make-the-text-overlaying-the-image layout active via other media-query-guarded CSS rules).  And below 37.5em, the gray-text rule will continue to be active; and above 37.5em, the white-text rule will continue to be active.
