### ISSUE TITLE
[Telemetry] Improve categories for Glean metrics

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-mobile/fenix#5150]
**This is not about collecting new data**

Glean supports metric categories and names in order to better organize the data being collected. Currently, Fenix [adds all events to the `events` category](https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml#L8) and most metrics to the `metrics` category. While this is not forbidden, the [documentation discourages this](https://mozilla.github.io/glean/book/user/adding-new-metrics.html#naming-things).

A different grouping could be used instead. For example, for search related data, things could be changed to:

```yaml
search:
  shortcuts_opened:
    type: event
    ...

   bar_tapped:
    type: event
    ...

  count:
    type: labeled_counter
    ...
```

While changing this for existing metrics could have impact on existing analyses, care should be taken moving forward.
