### ISSUE TITLE
[webcontent] :hover styles (randomly?) applied when scrolling on who.int page

### ISSUE THREAD

**Issue by miketaylr** [mozilla-mobile/fenix#9860]
Originally reported @ https://github.com/webcompat/web-bugs/issues/50647

This has nothing to do with TP.

STR:

1. go to https://www.who.int/news-room/q-a-detail/q-a-coronaviruses
2. start scrolling down to see the accordion questions

Expected: nothing, really
Actual: the question items get seemingly random :hover styles triggered - not where your finger was, or where it ended up. It's a bit weird. This is the CSS that's getting applied:

```css
.qa-details__content .sf-accordion__trigger-panel:hover::before {
    height: calc(100% - 10px);
}
.qa-details__content .sf-accordion__trigger-panel::before {
    content: '';
    position: absolute;
    top: 5px;
    left: 0;
    left: 0;
    width: 4px;
    height: 0;
    background-color: #008dc9;
    transition: all 0.3s ease;
}
```
